name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Chain
        run: |
          python clc.py clc.cl -o clc
          chmod +x clc
          ./clc cslc.cl -o cslc
          chmod +x cslc
          rm clc.py
          ./cslc examples/hello.csl -o examples/hello.cl
          ./clc examples/hello.cl -o examples/hello.elf
          ./cslc examples/fibonacci.csl -o examples/fibonacci.cl
          ./clc examples/fibonacci.cl -o examples/fibonacci.elf
          ./cslc examples/function.csl -o examples/function.cl
          ./clc examples/function.cl -o examples/function.elf

      - name: Verify bin sizes
        run: |
          stat -c%s examples/hello.elf
          stat -c%s examples/fibonacci.elf
          stat -c%s examples/function.elf
